version: 2.1

orbs:
  slack: circleci/slack@4.2.0

parameters:
  src-repo-url:
    type: string
    default: https://github.com/AEFeinstein/Super-2021-Swadge-FW-Sandbox.git
  windows-artifact:
    type: string
    default: swadge-chainsaw-windows.zip
  esp8266-artifact:
    type: string
    default: swadge-chainsaw-esp8266.zip

jobs:
  build-firmware:
    docker:
      - image: cimg/base:2020.01
    parameters:
      label:
        type: string
        default: swadge-chainsaw-firmware
    steps:
      - run:
          name: Update packages
          command: sudo apt-get update
      - run:
          name: Install dependencies
          command: sudo apt-get -y install build-essential make curl unrar-free autoconf automake libtool gcc g++ gperf flex bison texinfo gawk ncurses-dev libexpat-dev sed git unzip bash help2man wget bzip2 libtool-bin python-dev python python-serial python3-pip zip
      - run:
          name: Install python dependencies
          command: pip3 install pillow rtttl
      - run:
          name: Download toolchain
          command: wget https://github.com/cnlohr/esp82xx_bin_toolchain/raw/master/esp-open-sdk-x86_64-20200810.tar.xz
      - run:
          name: Unzip toolchain
          command: tar xJvf esp-open-sdk-x86_64-20200810.tar.xz
      - run:
          name: Set SDK environment variable
          command: echo 'export ESP_ROOT=$HOME/project/esp-open-sdk' >> $BASH_ENV
      - run:
          name: Append xtenxa bin to PATH
          command: echo 'export PATH=$HOME/project/esp-open-sdk/xtensa-lx106-elf/bin:$PATH' >> $BASH_ENV
      - run:
          name: Clone Repository
          command: git clone << pipeline.parameters.src-repo-url >> --recurse-submodules
      - run:
          name: Build Swadge
          working_directory: Super-2021-Swadge-FW-Sandbox/firmware
          command: unset ESP_GDB && export SET_SWADGE_VERSION=5 && make -j$(nproc) all debug
      - run:
          name: Store version information
          working_directory: Super-2021-Swadge-FW-Sandbox/firmware
          command: echo $(date) >> version.txt && echo "https://github.com/AEFeinstein/Super-2021-Swadge-FW-Sandbox/commit/${CIRCLE_SHA1}" >> version.txt
      - run:
          name: Create a ZIP of firmware
          working_directory: Super-2021-Swadge-FW-Sandbox/firmware
          command: zip -j << pipeline.parameters.esp8266-artifact >> version.txt image* assets.bin ESP8266_NONOS_SDK/bin/blank.bin ESP8266_NONOS_SDK/bin/esp_init_data_default_v08.bin
      - run:
          name: Add pyFlashGui to the ZIP
          working_directory: Super-2021-Swadge-FW-Sandbox/pyFlashGui
          command: zip -r ../firmware/<< pipeline.parameters.esp8266-artifact >> .
      - store_artifacts:
          path: Super-2021-Swadge-FW-Sandbox/firmware/<< pipeline.parameters.esp8266-artifact >>
#      - slack/notify:
#          event: pass
#          custom: |
#            {
#              "blocks": [
#                {
#                  "type": "section",
#                  "text": {
#                    "type": "mrkdwn",
#                    "text": "Fresh hot build!"
#                  }
#                },
#                {
#                  "type": "divider"
#                },
#                {
#                  "type": "section",
#                  "text": {
#                    "type": "mrkdwn",
#                    "text": ":esp8266-icon: ESP Build\nhttps://${CIRCLE_BUILD_NUM}-236183421-gh.circle-artifacts.com/0/Super-2021-Swadge-FW-Sandbox/firmware/<< pipeline.parameters.esp8266-artifact >>"
#                  }
#                }
#              ]
#            }

  build-windows:
    machine:
      image: windows-server-2019-vs2019:stable
      shell: bash.exe
    resource_class: windows.medium
    parameters:
      label:
        type: string
        default: swadge-chainsaw-windows
    steps:
      - run:
          name: Download Cygwin installer
          command: curl -sSJOL https://cygwin.com/setup-x86_64.exe
      - run:
          name: Install Cygwin and required packages
          shell: powershell.exe
          command: |
            .\setup-x86_64.exe -q -s https://mirrors.kernel.org/sourceware/cygwin/ -P git,gcc-core,make,zip,find,python3,python38,python38-devel,python38-pip,python38-imaging
            $env:Path = "C:\cygwin64\bin\;" + $env:Path
      - run:
          name: Setup Python
          shell: C:\\cygwin64\\bin\\bash.exe --login -eo pipefail
          command: |
            alias python3='python3.8'
            alias python='python3.8'
            # pip3 install --upgrade pip
            pip3 install rtttl
      - run:
          name: Clone and build Swadge
          shell: C:\\cygwin64\\bin\\bash.exe --login -eo pipefail
          command: |
            alias python3='python3.8'
            alias python='python3.8'
            CIRCLE_WORKING_DIRECTORY=$(eval "echo $CIRCLE_WORKING_DIRECTORY")
            mkdir -p $CIRCLE_WORKING_DIRECTORY
            cd $CIRCLE_WORKING_DIRECTORY
            git clone << pipeline.parameters.src-repo-url >> --recurse-submodules
            cd Super-2021-Swadge-FW-Sandbox/firmware
            unset ESP_GDB && export SET_SWADGE_VERSION=5 && make -C emu all
            echo $(date) >> version.txt && echo "https://github.com/AEFeinstein/Super-2021-Swadge-FW-Sandbox/commit/${CIRCLE_SHA1}" >> version.txt
            zip << pipeline.parameters.windows-artifact >> -j emu/swadgemu.exe emu/assets.bin version.txt /bin/cygwin1.dll
            pwd
            ls -lar
      - run:
          name: Bash Recursive ls
          shell: C:\\cygwin64\\bin\\bash.exe --login -eo pipefail
          command: ls -laR /
      - run:
          name: Recursive ls
          shell: powershell.exe
          command: |
            Get-ChildItem -Recurse
      - store_artifacts:
          path: Super-2021-Swadge-FW-Sandbox\\firmware\\<< pipeline.parameters.windows-artifact >>
#      - slack/notify:
#          event: pass
#          custom: |
#            {
#              "blocks": [
#                {
#                  "type": "section",
#                  "text": {
#                    "type": "mrkdwn",
#                    "text": "Fresh hot build!"
#                  }
#                },
#                {
#                  "type": "divider"
#                },
#                {
#                  "type": "section",
#                  "text": {
#                    "type": "mrkdwn",
#                    "text": ":windows95: Windows Build\nhttps://${CIRCLE_BUILD_NUM}-236183421-gh.circle-artifacts.com/0/Super-2021-Swadge-FW-Sandbox/firmware/<< pipeline.parameters.windows-artifact >>"
#                  }
#                }
#              ]
#            }

workflows:
  version: 2
  build-firmware-windows:
    jobs:
      - build-windows:
          filters:
            branches:
              only: master
#      - build-firmware:
#          filters:
#            branches:
#              only: master
